install.packages(c("janitor",
                   "here",
                   "tmap",
                   "sf",
                   "sp",
                   "dplyr",
                   "ggplot2",
                   "patchwork",
                   "gt"))